networks:
    internal:

services:
    nginx:
        image: nginx:latest
        container_name: nginx_intas
        ports:
          - "8080:80"
        volumes:
          - $PWD:/var/www
          - ./docker/nginx:/etc/nginx/conf.d
          - ./logs/nginx:/var/log/nginx
        depends_on:
          - phpfpm
          - database
        networks:
          - internal
    phpfpm:
        build:
          context: ./docker/phpfpm
          dockerfile: Dockerfile
        container_name: phpfpm_intas
        volumes:
          - $PWD:/var/www
          - ./docker/phpfpm:/usr/local/etc/php/php.ini
        ports:
          - "9000:9000"
        networks:
          - internal
    database:
      container_name: postgres_intas
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_HOST_AUTH_METHOD:
      ports:
        - "5434:5432"
      volumes:
        - ./logs/pgsql:/var/log/pgsql
      networks:
        - internal